---
- hosts: all
  sudo: true
  tasks:
    - name: update apt repo
      apt: update-cache=yes cache_valid_time=3600

    - name: upgrade all packages
      apt: upgrade=dist

    - name: set hostname
      hostname: name=dev

    - name: install common tools
      apt: name={{ item }} state=installed
      with_items:
        - git
        - mercurial

- include: virtualenv/virtualenv.yml
- include: mysql/mysql.yml
- include: postgresql/postgresql.yml
- include: rabbitmq/rabbitmq.yml
- include: memcache/memcache.yml
