---
- name: install mysql
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb

- name: create mysql root password
  command: /usr/bin/openssl rand -base64 16
  register: mysql_root_pass

- name: make mysql run on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"

- name: copy .my.cnf 
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: update mysql root password
  mysql_user: 
    login_user: root
    login_password: ""
    login_host: "localhost"
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_pass.stdout }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: allow remote root access
  mysql_user:
    name: "root"
    host: "%" 
    password: "{{ mysql_root_pass.stdout }}"
    priv: "*.*:ALL,GRANT" 
    state: present

- name: delete anonymous mysql server user for localhost
  mysql_user: name="" state=absent

- name: remove the mysql test database
  mysql_db: name=test state=absent
  notify: restart mysql
