---
- include_vars: vault.yml

- name: Update apt repo
  become: yes
  apt: update-cache=yes

- name: Upgrade all packages
  become: yes
  apt: upgrade=dist

- name: install some packages
  become: yes
  apt: name="{{ item }}" state=installed
  with_items:
    - sudo
    - ntp
    - monit
    - python
    - python-dev
    - python-setuptools
    - mercurial
    - libssl-dev
    - libffi-dev

- name: Install pip
  become: yes
  easy_install: name=pip

- name: set hostname
  become: yes
  hostname: name="{{ inventory_hostname }}"

- name: create system user
  become: yes
  user: name="{{ user }}"  shell=/bin/bash

- name: create .ssh folder
  become: yes
  file: path="/home/{{ user }}/.ssh" state=directory mode=0700 owner={{ user }} group={{ user }}

- name: install authorized keys
  become: yes
  authorized_key: user="{{ user }}" key="{{ user_public_key }}"

- name: set short hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }}'
    owner: root
    group: root
    mode: 0644
    insertafter: EOF
    state: present

- name: Disable empty password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd

# - name: Disable password login
#   lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
#   notify: restart sshd

# - name: Enable PAM
#   lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
#   notify: restart sshd

- name: install monit conf
  become: yes
  template: src=monit.conf dest=/etc/monit/conf.d/default.conf mode=0400
